sudo: required
language: bash
services:
  - docker
before_script:
  - docker-compose build
  - docker-compose run php composer install
  - docker-compose run php ./vendor/bin/phpcs --standard=psr2 --ignore=vendor -n .
  - docker-compose run php ./vendor/bin/phpstan analyse  --level=7 ./src ./tests ./main.php
script: docker-compose run php php ./tests/run.php
after_success:
  - docker images
deploy:
  provider: script
  skip_cleanup: true
  script: ./deploy.sh
  on:
    tags: true
